
services:

# ─────────────────────
# API FastAPI
# ─────────────────────
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accidents_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./api:/app/api


# ─────────────────────
# MLflow tracking server
# ─────────────────────
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow_server
    working_dir: /mlflow
    volumes:
      - ./mlflow:/mlflow
    ports:
      - "8080:8080"

    #version serveur local / docker
    #command: 
    #  - mlflow
    #  - server
    #  - --host
    #  - 0.0.0.0
    #  - --port
    #  - "8080"
    #  - --backend-store-uri sqlite:///mlflow.db
    #  - --default-artifact-root /mlflow/mlruns
    #  - --serve-artifacts

    #version Serveur tracker via DAgshub / Mlflow / Docker pour conserver tous mes runs et versions de modele 
    environment:
      # Ces variables permettent au conteneur Docker de se connecter à DagsHub
    - MLFLOW_TRACKING_URI=https://dagshub.com/Melanie94480/mlops-melanie.mlflow
    - MLFLOW_TRACKING_USERNAME=${MLFLOW_USERNAME}
    - MLFLOW_TRACKING_PASSWORD=${MLFLOW_PASSWORD}
    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "8080"    


# ─────────────────────
# Prometheus
# ─────────────────────
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api


# ─────────────────────
# Grafana
# ─────────────────────
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus


volumes:
  grafana_data:
