stages:
  import_data:
    cmd: python src/data/import_raw_data.py
    outs:
      - data/raw

  preprocess:
    cmd: python src/data/make_dataset.py
    deps:
      - data/raw
      - src/data/make_dataset.py
    outs:
      - data/preprocessed

  train:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/preprocessed
    outs:
      - src/models/trained_model.joblib

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - src/models/trained_model.joblib
    metrics:
      - metrics/evaluation_metrics.json

