worker_processes  auto;

events {
    worker_connections  1024;
}
http {
    include       mime.types;
    sendfile        on;
    keepalive_timeout  65;
    #gzip  on;

    upstream apis {
        server api:8000;
}
    server {
        listen       80;
        server_name  localhost;
        return 301 https://$host$request_uri;
    }

    server {
       listen       443 ssl;
       server_name  localhost;

       ssl_certificate      /etc/nginx/certs/nginx.crt;
       ssl_certificate_key  /etc/nginx/certs/nginx.key;

       ssl_protocols TLSv1.2 TLSv1.3;
       ssl_ciphers  HIGH:!aNULL:!MD5;
       ssl_prefer_server_ciphers  on;
       
       location / {
        proxy_pass http://apis;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}